### ISSUE TITLE
RMC not visible in HTML5

### ISSUE THREAD

**Issue by whccxt** [TriAxis-Games/RealtimeMeshComponent#261]
Hi,

I tried to generate RMC in html5 (UE4.23). It worked well in editor mode but not in HTML5 mode.

I used "create section from component" node in blueprint. 

Would anyone has good suggections?

Thanks a lot!

Ting

**Comment by Koderz** [comment]
Hey @whccxt 

I really don't attempt to support HTML5 at this point due to Epic dropping support and very limited interest in it from my experience. So closing this. If you need assistance, feel free to reach out to me on Discord and I can attempt to help but I don't even have engine versions < 4.27 setup at this point.

-Chris
