### ISSUE TITLE
UpdateSectionGroup fix

### ISSUE THREAD

**Issue by CitizenCEO** [TriAxis-Games/RealtimeMeshComponent#271]
UpdateSectionGroup has a problem which will empty all other buffers when supplementing incomplete stream set

Following edits in source code fixes these problems:

```
FILE: 
RealtimeMeshSectionGroup.cpp LINE 236

FROM:
if (!InStreams.Contains(StreamKey))

TO:
if (InStreams.Contains(StreamKey))
```

This removes only the streams that were supplemented in parameters
Will this be reflected in the next update?
I would love to do merge request but have no idea how to do that... Even tho I work as a gamedev 😳

**Comment by VintageDeveloper** [comment]
Hi there, I've put in a pull request with this suggestion, I've also added you as the **co-author of the commit**. 🙂 

Pull Requests are a lot of fun! I've written below how to do them:

**1. Create a fork of the repo:**

![1 CreateFork](https://github.com/TriAxis-Games/RealtimeMeshComponent/assets/149346422/9d43b0ad-5f43-4f3a-937b-20a74199a866)


**2. Clone this fork locally and commit and push any changes you'd like to make.**


**3. On Github, go to your fork repo, and select "pull request":**

![3  Select Pull Request](https://github.com/TriAxis-Games/RealtimeMeshComponent/assets/149346422/128ec380-25de-4b59-8342-e7e9bec587fb)


**4. In the new window, press "new pull request":**

![4  Select](https://github.com/TriAxis-Games/RealtimeMeshComponent/assets/149346422/7b9aa8ff-f23e-4d2e-970d-0afb18071ed0)

**5. Then select, "Create Pull Request"**

![5  Make Request](https://github.com/TriAxis-Games/RealtimeMeshComponent/assets/149346422/44c30697-8e43-4ddd-ab8a-fd5cd83121d6)

**6. Then just add any details about the pull request.**

**Comment by Koderz** [comment]
Hey @CitizenCEO 

That is actually correct for that function as that function is supposed to replace all existing streams.   I could make a separate function that could supplement the streams with the ones you're adding, but that function is `SetAllStreams` so by design it's supposed to remove any streams you aren't supplying, and update or create if necessary the ones you're supplying.

Hopefully that helps?

If I'm misunderstanding what you're trying to say feel free to reopen this issue.

Thanks
-Chris
